/* eslint-disable no-undef */

const KAKAO_JAVASCRIPT_APP_KEY = process.env.REACT_APP_KAKAO_JAVASCRIPT_APP_KEY

const KAKAO_REST_API_APP_KEY = process.env.REACT_APP_KAKAO_REST_API_APP_KEY

const SERVER_DOMAIN_URL = process.env.REACT_APP_SERVER_DOMAIN_URL

export { KAKAO_JAVASCRIPT_APP_KEY, KAKAO_REST_API_APP_KEY, SERVER_DOMAIN_URL }
